import "dotenv/config";import express from "express";import http from "http";import cors from "cors";import crypto from "crypto";import jwt from "jsonwebtoken";import mongoose from "mongoose";import {Server} from "socket.io";
const app=express(),server=http.createServer(app),PORT=process.env.PORT||3000,FRONT=(process.env.FRONTEND_URL||"http://localhost:5500").replace(/\/$/,""),SECRET=process.env.JWT_SECRET||"change-me";
app.use(cors({origin:FRONT,credentials:true}));app.use(express.json());app.get("/health",(q,r)=>r.json({ok:true,service:"miniverse-backend"}));
const User=mongoose.model("User",new mongoose.Schema({discordId:{type:String,unique:true,sparse:true},username:String,displayName:String,avatarUrl:String,demo:Boolean,wins:{type:Number,default:0},losses:{type:Number,default:0},games:{type:Number,default:0},lastSeen:Date}));let db=false,mem=new Map();
try{if(process.env.MONGODB_URI){await mongoose.connect(process.env.MONGODB_URI);db=true;console.log("MongoDB connected")}}catch(e){console.error("MongoDB:",e.message)} 
const get=async id=>db?(await User.findById(id))||mem.get(id):mem.get(id),makeMem=(id,d)=>{let u=mem.get(id)||{_id:id,...d,wins:0,losses:0,games:0};mem.set(id,u);return u},sign=u=>jwt.sign({sub:u._id||u.id,username:u.username,displayName:u.displayName},SECRET,{expiresIn:"7d"}),pub=(u,id)=>({id:id||u._id,username:u.username,displayName:u.displayName,avatarUrl:u.avatarUrl,wins:u.wins||0,losses:u.losses||0,games:u.games||0});
async function auth(q,r,n){try{let p=jwt.verify((q.headers.authorization||"").replace("Bearer ",""),SECRET),u=await get(p.sub);if(!u)throw Error();q.user=u;q.uid=p.sub;n()}catch{r.status(401).json({error:"Authentication required"})}}function sa(s,n){try{s.user=jwt.verify(s.handshake.auth?.token,SECRET);n()}catch{n(Error("Unauthorized"))}}
const avatars=["😎","👩🏻","👨🏼","👩🏿","🧑🏻‍🦰","👩🏽","👱🏻","👩🏾","🧑🏽","👩🏻‍🦰","🧔🏿","👱🏼","👨🏿","👩🏻‍🦰","👨🏽","👩🏿","👱🏻","👩🏽","🧔🏻‍🦰","👩🏿","🧔🏽","👱🏻","👨🏿","👩🏽‍🦰","👨🏼","👩🏻","🧔🏿","👩🏽","🧔🏽‍🦰","👱🏽"],names=["Alex","Maya","Leo","Nora","Ryan","Zara","Ethan","Luna","Noah","Ava","Kai","Ivy","Owen","Mia","Adam","Ella","Finn","Sia","Liam","Zoe","Max","Aria","Ben","Nia","Sam","Eva","Jay","Lia","Cole","Ria"],cats=[["gender","Gender","⚧","Male?"],["eyes","Eye Color","👁","Blue eyes?"],["hairStyle","Hair","💇","Curly hair?"],["hairColor","Hair Color","🎨","Black hair?"],["skin","Skin Tone","🖐","Light skin?"],["glasses","Glasses","👓","Glasses?"],["headwear","Headwear","🎩","Hat?"],["jewelry","Accessories","💎","Jewelry?"],["facialHair","Facial Hair","🧔","Facial hair?"]];
const sockets=new Map(),rooms=new Map(),queue=[],invites=new Map(),io=new Server(server,{cors:{origin:FRONT,methods:["GET","POST"]}});io.use(sa);
const people=()=>[...sockets].map(([id,x])=>({id,displayName:x.displayName,avatarUrl:x.avatarUrl,status:x.room?"in-game":"online"})),broadcast=()=>io.emit("players:update",people());
function room(a,b,demo=false){let id=crypto.randomUUID(),A=sockets.get(a),B=sockets.get(b),sa=crypto.randomInt(0,30),sb=crypto.randomInt(0,30);if(sa===sb)sb=(sb+1)%30;let r={id,a,b,turn:a,round:1,status:"playing",demo,p:{[a]:{id:a,displayName:A.displayName,secret:sa,dead:[],used:new Set()},[b]:{id:b,displayName:B.displayName,secret:sb,dead:[],used:new Set()}}};rooms.set(id,r);A.room=id;B.room=id;A.socket.join(id);B.socket.join(id);broadcast();state(r,a);state(r,b)}
function state(r,id){let p=r.p[id],o=r.p[id===r.a?r.b:r.a],s=sockets.get(id);if(!s)return;s.socket.emit("game:state",{turn:r.turn,round:r.round,opponentRemaining:30-o.dead.length,characters:avatars.map((avatar,i)=>({id:String(i),avatar,name:names[i],short:i%2?"Female":"Male",eliminated:p.dead.includes(i)})),categories:cats.map(c=>({id:c[0],label:c[1],icon:c[2],example:c[3],used:p.used.has(c[0])}))})}
io.on("connection",s=>{let id=s.user.sub;sockets.set(id,{socket:s,displayName:s.user.displayName||s.user.username||"Player",avatarUrl:s.user.avatarUrl||"https://cdn.discordapp.com/embed/avatars/0.png",room:null});broadcast();
s.on("match:random",()=>{let x=queue.shift();if(x&&sockets.has(x))room(x,id);else{queue.push(id);s.emit("queue:status",{message:"Searching public players…"})}});s.on("match:cancel",()=>{let i=queue.indexOf(id);if(i>=0)queue.splice(i,1)});
s.on("match:demo",()=>{let bot="bot_"+id;sockets.set(bot,{socket:s,displayName:"Demo Bot",avatarUrl:"https://cdn.discordapp.com/embed/avatars/1.png",room:null});room(id,bot,true)});
s.on("invite:send",({to})=>{let x=sockets.get(to);if(!x||x.room)return;let k=crypto.randomUUID();invites.set(k,{from:id,to});x.socket.emit("invite:received",{id:k,from:{displayName:s.user.displayName||"Player"}})});s.on("invite:accept",({inviteId})=>{let x=invites.get(inviteId);if(!x||x.to!==id)return;invites.delete(inviteId);if(sockets.has(x.from))room(x.from,id)});s.on("invite:decline",({inviteId})=>{let x=invites.get(inviteId);if(x){invites.delete(inviteId);sockets.get(x.from)?.socket.emit("invite:declined")}});
s.on("game:question",({category})=>{let r=[...rooms.values()].find(x=>x.a===id||x.b===id);if(!r||r.turn!==id)return;let p=r.p[id],o=r.p[id===r.a?r.b:r.a];if(p.used.has(category))return;p.used.add(category);let answer=Math.random()>.5;o.dead=[...new Set(o.dead.concat([...Array(30).keys()].filter(i=>i!==o.secret).filter(i=>((i+category.length)%2===0)!==answer)))];r.turn=o.id;r.round++;state(r,r.a);state(r,r.b);s.emit("toast_question",{category,answer})});
s.on("game:guess",async({characterId})=>{let r=[...rooms.values()].find(x=>x.a===id||x.b===id);if(!r||r.turn!==id)return;let p=r.p[id],o=r.p[id===r.a?r.b:r.a],g=+characterId,win=g===o.secret,w=win?id:o.id;r.status="ended";if(win){for(let [uid,field] of [[w,"wins"],[w===r.a?r.b:r.a,"losses"]]){if(String(uid).startsWith("bot_"))continue;let u=await get(uid);if(u){u[field]++;u.games++;if(db)await u.save()}}}for(let uid of [r.a,r.b])sockets.get(uid)?.socket.emit("game:ended",{winnerId:w,reason:win?`${names[g]} was the secret character.`:`Wrong guess. ${names[g]} was not the secret.`});broadcast()});
s.on("game:rematch",()=>{let r=[...rooms.values()].find(x=>x.a===id||x.b===id);if(!r)return;let o=r.a===id?r.b:r.a;if(!o.startsWith("bot_"))return;for(let p of Object.values(r.p)){p.dead=[];p.used=new Set();p.secret=crypto.randomInt(0,30)}while(r.p[r.a].secret===r.p[r.b].secret)r.p[r.b].secret=crypto.randomInt(0,30);r.status="playing";r.turn=id;r.round=1;state(r,r.a);state(r,r.b)});
s.on("disconnect",()=>{sockets.delete(id);let i=queue.indexOf(id);if(i>=0)queue.splice(i,1);let r=[...rooms.values()].find(x=>x.a===id||x.b===id);if(r&&r.status==="playing"){let o=r.a===id?r.b:r.a;sockets.get(o)?.socket.emit("game:ended",{winnerId:o,reason:"Opponent disconnected."});r.status="ended"}broadcast()})});
app.post("/api/demo-login",(q,r)=>{let id="demo_"+crypto.randomUUID(),u=makeMem(id,{username:"demo",displayName:"Demo Player",avatarUrl:"https://cdn.discordapp.com/embed/avatars/0.png",demo:true});r.json({token:sign(u),user:pub(u,id)})});app.get("/api/me",auth,(q,r)=>r.json({user:pub(q.user,q.uid)}));app.get("/api/stats",auth,async(q,r)=>{let u=await get(q.uid);r.json({stats:{wins:u.wins||0,losses:u.losses||0,games:u.games||0}})});app.get("/api/leaderboard",async(q,r)=>{let a=db?await User.find({demo:false}).sort({wins:-1,games:-1}).limit(100).lean():[...mem.values()].filter(x=>!x.demo);r.json({players:a.map(x=>({displayName:x.displayName,avatarUrl:x.avatarUrl,wins:x.wins||0,games:x.games||0,winRate:x.games?Math.round(x.wins/x.games*100):0}))})});
app.get("/auth/discord",(q,r)=>{let u=new URLSearchParams({client_id:process.env.DISCORD_CLIENT_ID||"",response_type:"code",redirect_uri:process.env.DISCORD_REDIRECT_URI||"",scope:"identify"});r.redirect("https://discord.com/oauth2/authorize?"+u)});app.get("/auth/discord/callback",async(q,r)=>{try{let b=new URLSearchParams({client_id:process.env.DISCORD_CLIENT_ID,client_secret:process.env.DISCORD_CLIENT_SECRET,grant_type:"authorization_code",code:q.query.code,redirect_uri:process.env.DISCORD_REDIRECT_URI}),x=await fetch("https://discord.com/api/oauth2/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:b}),t=await x.json();if(!x.ok)throw Error();let u=await fetch("https://discord.com/api/users/@me",{headers:{Authorization:`Bearer ${t.access_token}`}}),p=await u.json(),a;if(db)a=await User.findOneAndUpdate({discordId:p.id},{discordId:p.id,username:p.username,displayName:p.global_name||p.username,avatarUrl:p.avatar?`https://cdn.discordapp.com/avatars/${p.id}/${p.avatar}.png?size=128`:"https://cdn.discordapp.com/embed/avatars/0.png",lastSeen:new Date()},{upsert:true,new:true});else a=makeMem("d_"+p.id,{username:p.username,displayName:p.global_name||p.username,avatarUrl:p.avatar?`https://cdn.discordapp.com/avatars/${p.id}/${p.avatar}.png?size=128`:"https://cdn.discordapp.com/embed/avatars/0.png"});r.redirect(`${FRONT}/#token=${encodeURIComponent(sign(a))}`)}catch(e){r.status(400).send("Discord login failed")}});server.listen(PORT,()=>console.log("MiniVerse backend listening",PORT));