import "dotenv/config";
import express from "express";
import http from "http";
import cors from "cors";
import crypto from "crypto";
import jwt from "jsonwebtoken";
import mongoose from "mongoose";
import { Server } from "socket.io";

const app=express();
const server=http.createServer(app);
const PORT=process.env.PORT||3000;
const FRONT=(process.env.FRONTEND_URL||"http://localhost:5500").replace(/\/$/,"");
const SECRET=process.env.JWT_SECRET||"change-me";
app.use(cors({origin:FRONT,credentials:true}));
app.use(express.json());
app.get('/health',(req,res)=>res.json({ok:true,service:'miniverse-v3',time:new Date().toISOString()}));

const User=mongoose.model('User',new mongoose.Schema({discordId:{type:String,unique:true,sparse:true},username:String,displayName:String,avatarUrl:String,demo:Boolean,wins:{type:Number,default:0},losses:{type:Number,default:0},games:{type:Number,default:0},lastSeen:Date}));
let db=false;
try{ if(process.env.MONGODB_URI){await mongoose.connect(process.env.MONGODB_URI);db=true;console.log('MongoDB connected')} }catch(e){console.warn('MongoDB unavailable; using memory mode:',e.message)}
const mem=new Map();
const makeMem=(id,data)=>{const u=mem.get(id)||{_id:id,wins:0,losses:0,games:0,...data};mem.set(id,u);return u};
const getUser=async id=>db?((await User.findById(id))||mem.get(id)):mem.get(id);
const saveUser=async u=>{if(db && u?.save) await u.save(); else if(u?._id) mem.set(u._id,u)};
const pub=(u,id)=>({id:id||u._id,username:u.username,displayName:u.displayName,avatarUrl:u.avatarUrl,wins:u.wins||0,losses:u.losses||0,games:u.games||0});
const sign=u=>jwt.sign({sub:u._id||u.id,username:u.username,displayName:u.displayName,avatarUrl:u.avatarUrl},SECRET,{expiresIn:'7d'});
function auth(req,res,next){try{const token=(req.headers.authorization||'').replace(/^Bearer\s+/,'');const p=jwt.verify(token,SECRET);getUser(p.sub).then(u=>{if(!u)throw 0;req.uid=p.sub;req.user=u;next()}).catch(()=>res.status(401).json({error:'Authentication required'}))}catch{res.status(401).json({error:'Authentication required'})}}

const CHARACTERS=[
['Lucy','female','long','black','brown','light',0,1,1,'none','#e95c55','#f1a36b','#17110e'],['Tom','male','short','brown','blue','olive',1,0,0,'mustache','#6875d9','#f0a46f','#66341f'],['Sara','female','long','black','blue','light',1,1,1,'none','#7c5aaa','#f2b17d','#24172f'],['Emma','female','long','gray','brown','dark',0,0,1,'none','#8e75c5','#75452f','#cfd3df'],['Henry','male','short','brown','brown','dark',0,0,0,'beard','#4771a9','#7b432f','#3a241d'],['Rose','female','long','black','blue','light',0,1,0,'none','#a879b9','#efbd9a','#17120f'],['Jeff','male','short','blonde','blue','light',1,0,0,'mustache','#f1b52c','#f2bd82','#f4bd31'],['Lia','female','long','gray','brown','olive',0,0,1,'none','#54b1b0','#d99c74','#cfd3df'],['Rob','male','short','black','brown','olive',0,1,0,'beard','#c64e38','#d58b52','#16120f'],['Aria','female','long','gray','green','light',1,0,0,'none','#e8a3c5','#e7c1a4','#d2d4df'],['Bob','male','short','black','brown','dark',0,0,0,'mustache','#4397a8','#75402d','#17120f'],['Bella','female','long','red','green','light',0,0,1,'none','#5bbf87','#efc0a1','#c95b2f'],['Sophia','female','long','blonde','brown','light',0,0,1,'none','#e15d78','#eebc78','#f4bd31'],['Jack','male','short','gray','green','olive',0,1,0,'beard','#7b52a8','#c18c6d','#cfd3df'],['Jose','male','short','black','green','dark',0,0,0,'beard','#3996a1','#78412d','#17120f'],['Theo','male','short','blonde','blue','light',0,0,0,'none','#5794d6','#f0c087','#f4bd31'],['Annie','female','long','red','brown','light',0,0,1,'none','#ce715d','#edb58e','#c95b2f'],['Paul','male','short','red','green','olive',0,0,0,'beard','#ce7950','#e4a172','#c95b2f'],['Olivia','female','long','black','green','dark',0,0,1,'none','#397fa9','#70412e','#17120f'],['Chloe','female','long','brown','green','light',0,0,1,'none','#d87878','#e4a77f','#66341f'],['Nora','female','long','black','brown','dark',1,1,1,'none','#5caa6e','#81472e','#17120f'],['James','male','short','brown','brown','light',1,1,0,'mustache','#57a9a3','#e9bd9c','#66341f'],['Bill','male','short','blonde','brown','light',0,1,0,'none','#e4a72e','#f1c18e','#f4bd31'],['Julia','female','long','gray','brown','dark',0,0,1,'none','#c59d34','#6f3f2f','#cfd3df'],['Naomi','female','long','black','brown','light',0,0,1,'none','#e45e82','#f0c0ad','#17120f'],['Ryan','male','short','brown','blue','olive',1,1,0,'mustache','#6e6554','#e2ad84','#66341f'],['David','male','short','black','brown','dark',0,0,0,'mustache','#2f7b91','#5d301f','#15100e'],['Mila','female','long','black','brown','dark',1,0,1,'none','#df6d63','#7b412d','#17120f'],['John','male','short','gray','blue','dark',0,1,0,'beard','#b8a27d','#71422d','#cfd3df'],['Ben','male','short','black','brown','dark',1,0,0,'mustache','#3988a1','#7b432c','#17120f']
].map((x,i)=>({id:i,name:x[0],gender:x[1],hairStyle:x[2],hairColor:x[3],eyes:x[4],skin:x[5],glasses:!!x[6],headwear:!!x[7],jewelry:!!x[8],facialHair:x[9],shirt:x[10],skinColor:x[11],hair:x[12]}));
const CATS={
 gender:{title:'GENDER',icon:'🧑',choices:[['👨','MALE','male'],['👩','FEMALE','female']]},
 eyes:{title:'EYE COLOR',icon:'👁️',choices:[['🔵','BLUE','blue'],['🟢','GREEN','green'],['🟤','BROWN','brown']]},
 hairStyle:{title:'HAIR',icon:'💇',choices:[['🧑‍🦲','BALD','bald'],['💇','SHORT','short'],['👩','LONG','long']]},
 hairColor:{title:'HAIR COLOR',icon:'🎨',choices:[['🤎','BROWN','brown'],['🖤','BLACK','black'],['💛','BLONDE','blonde'],['🩶','GRAY','gray'],['❤️','RED','red']]},
 skin:{title:'SKIN TONE',icon:'🖐️',choices:[['🟠','OLIVE','olive'],['🟡','LIGHT','light'],['🟤','DARK','dark']]},
 accessories:{title:'ACCESSORIES',icon:'👓',choices:[['🚫','NONE','none'],['👓','GLASSES','glasses'],['🎩','HEADWEAR','headwear'],['💎','JEWELRY','jewelry']]},
 facialHair:{title:'FACIAL HAIR',icon:'🧔',choices:[['🙂','NONE','none'],['👨','MUSTACHE','mustache'],['🧔','BEARD','beard']]}
};
function attr(c,k,v){if(k==='accessories')return v==='none'?(!c.glasses&&!c.headwear&&!c.jewelry):v==='glasses'?c.glasses:v==='headwear'?c.headwear:v==='jewelry'?c.jewelry:false;return c[k]===v}
function eliminate(list,k,v,ans){return list.filter(c=>attr(c,k,v)===ans)}

const io=new Server(server,{cors:{origin:FRONT,methods:['GET','POST']}});
const sockets=new Map(),queues={guess:[],quick:[],memory:[],connect:[],number:[]},rooms=new Map(),invites=new Map();
function publicPeople(){return [...sockets].map(([id,s])=>({id,displayName:s.displayName,avatarUrl:s.avatarUrl,status:s.room?'in-game':'online',game:s.game||null}))}
function broadcast(){io.emit('players:update',publicPeople())}
function findRoom(id){const s=sockets.get(id);return s?.room?rooms.get(s.room):[...rooms.values()].find(r=>r.players?.[id])}
function emitRoom(r,event,data){for(const id of Object.keys(r.players||{}))sockets.get(id)?.socket.emit(event,data)}
function safeChars(){return CHARACTERS.map(c=>({id:c.id,name:c.name,gender:c.gender,hairStyle:c.hairStyle,hairColor:c.hairColor,eyes:c.eyes,skin:c.skin,glasses:c.glasses,headwear:c.headwear,jewelry:c.jewelry,facialHair:c.facialHair,shirt:c.shirt,skinColor:c.skinColor,hair:c.hair}))}
function guessState(r,id){const me=r.players[id],op=r.players[me.opponent];const state={mode:'guess',roomId:r.id,turn:r.turn,round:r.round,phase:r.phase,me:{id,displayName:me.displayName,secret:me.secret,eliminated:[...me.eliminated],used:[...me.used]},opponent:{id:me.opponent,displayName:op.displayName,eliminatedCount:op.eliminated.size,remaining:CHARACTERS.length-op.eliminated.size},characters:safeChars(),categories:Object.entries(CATS).map(([id,x])=>({id,title:x.title,icon:x.icon,choices:x.choices,used:me.used.has(id)})),winner:r.winner||null,lastQuestion:r.lastQuestion||null};sockets.get(id)?.socket.emit('guess:state',state)}
function endGame(r,winner,reason){r.phase='ended';r.winner=winner;r.reason=reason;emitRoom(r,'game:ended',{winnerId:winner,reason});for(const id of Object.keys(r.players)){const u=getUser(id);Promise.resolve(u).then(async user=>{if(!user)return;user.games=(user.games||0)+1;if(id===winner)user.wins=(user.wins||0)+1;else user.losses=(user.losses||0)+1;user.lastSeen=new Date();await saveUser(user)}).catch(()=>{})}broadcast()}
function createGuess(a,b){const sa=crypto.randomInt(0,30),sb=(()=>{let x=crypto.randomInt(0,30);while(x===sa)x=crypto.randomInt(0,30);return x})();const id='guess_'+crypto.randomUUID();const A=sockets.get(a),B=sockets.get(b);const r={id,mode:'guess',phase:'playing',turn:a,round:1,lastQuestion:null,players:{[a]:{id:a,displayName:A.displayName,secret:sa,eliminated:new Set(),used:new Set(),opponent:b},[b]:{id:b,displayName:B.displayName,secret:sb,eliminated:new Set(),used:new Set(),opponent:a}}};rooms.set(id,r);A.room=id;A.game='Guess Character';B.room=id;B.game='Guess Character';A.socket.join(id);B.socket.join(id);guessState(r,a);guessState(r,b);broadcast()}
function match(mode,id){const q=queues[mode];const idx=q.findIndex(x=>sockets.has(x)&&!sockets.get(x).room);if(idx>=0){const other=q.splice(idx,1)[0];createMode(mode,other,id)}else{if(!q.includes(id))q.push(id);sockets.get(id)?.socket.emit('queue:status',{mode,message:'Searching for a real player…',count:q.length})}}
function createMode(mode,a,b){if(mode==='guess')return createGuess(a,b);const id=mode+'_'+crypto.randomUUID();const A=sockets.get(a),B=sockets.get(b);const r={id,mode,phase:'ready',turn:a,players:{[a]:{id:a,displayName:A.displayName},[b]:{id:b,displayName:B.displayName}}};rooms.set(id,r);A.room=id;B.room=id;A.game=mode;B.game=mode;A.socket.join(id);B.socket.join(id);if(mode==='quick')startQuick(r);else if(mode==='memory')startMemory(r);else if(mode==='connect')startConnect(r);else if(mode==='number')startNumber(r);broadcast()}
function startQuick(r){r.phase='waiting';emitRoom(r,'quick:state',{phase:'waiting'});r.timer=setTimeout(()=>{r.goAt=Date.now();r.phase='go';emitRoom(r,'quick:state',{phase:'go',serverTime:r.goAt})},1500+crypto.randomInt(0,1800))}
function startMemory(r){r.phase='playing';r.turn=r.players[Object.keys(r.players)[crypto.randomInt(0,2)]].id;r.scores={};for(const id of Object.keys(r.players))r.scores[id]=0;r.deck=Array.from({length:8},(_,i)=>i).flatMap(x=>[x,x]).sort(()=>Math.random()-.5);r.revealed=[];r.matched=[];emitRoom(r,'memory:state',{phase:r.phase,turn:r.turn,deck:r.deck,matched:[],scores:r.scores})}
function startConnect(r){r.phase='playing';r.board=Array(42).fill(null);r.turn=Object.keys(r.players)[0];emitRoom(r,'connect:state',{board:r.board,turn:r.turn,winner:null})}
function startNumber(r){r.phase='ready';r.target=crypto.randomInt(10,100);r.startedAt=Date.now()+1200;emitRoom(r,'number:state',{phase:'countdown'});setTimeout(()=>{if(!rooms.has(r.id))return;r.phase='playing';r.target=crypto.randomInt(10,100);r.startedAt=Date.now();emitRoom(r,'number:state',{phase:'go',target:r.target,startedAt:r.startedAt})},1200)}
function checkConnect(board,idx){const row=Math.floor(idx/7),col=idx%7,dirs=[[1,0],[0,1],[1,1],[1,-1]];for(const[drow,dcol]of dirs){let n=1;for(const sign of [-1,1]){let rr=row+sign*drow,cc=col+sign*dcol;while(rr>=0&&rr<6&&cc>=0&&cc<7&&board[rr*7+cc]===board[idx]){n++;rr+=sign*drow;cc+=sign*dcol}}if(n>=4)return true}return false}

io.use((socket,next)=>{try{const p=jwt.verify(socket.handshake.auth?.token||'',SECRET);socket.user=p;next()}catch{next(new Error('Unauthorized'))}});
io.on('connection',socket=>{const id=socket.user.sub;const displayName=socket.user.displayName||socket.user.username||'Player';sockets.set(id,{socket,displayName,avatarUrl:socket.user.avatarUrl||'https://cdn.discordapp.com/embed/avatars/0.png',room:null,game:null});broadcast();
 socket.on('match:random',({mode='guess'}={})=>{if(!queues[mode])return;match(mode,id)});
 socket.on('match:cancel',({mode='guess'}={})=>{const q=queues[mode]||[];queues[mode]=q.filter(x=>x!==id);socket.emit('queue:cancelled')});
 socket.on('invite:send',({to,mode='guess'})=>{const target=sockets.get(to);if(!target||target.room)return socket.emit('toast',{message:'Player is already busy.'});const inviteId=crypto.randomUUID();invites.set(inviteId,{from:id,to,mode,created:Date.now()});target.socket.emit('invite:received',{id:inviteId,mode,from:{id,displayName,avatarUrl:sockets.get(id).avatarUrl}})});
 socket.on('invite:accept',({inviteId})=>{const inv=invites.get(inviteId);if(!inv||inv.to!==id)return;invites.delete(inviteId);if(sockets.has(inv.from)&&!sockets.get(inv.from).room&&!sockets.get(id).room)createMode(inv.mode,inv.from,id)});
 socket.on('invite:decline',({inviteId})=>{const inv=invites.get(inviteId);if(inv){invites.delete(inviteId);sockets.get(inv.from)?.socket.emit('toast',{message:'Invite declined.'})}});
 socket.on('guess:question',({category,value})=>{const r=findRoom(id);if(!r||r.mode!=='guess'||r.phase!=='playing'||r.turn!==id)return;const me=r.players[id],op=r.players[me.opponent],cat=CATS[category];if(!cat||me.used.has(category))return;me.used.add(category);const answer=attr(CHARACTERS[op.secret],category,value);const remaining=CHARACTERS.filter(c=>!me.eliminated.has(c.id));const newlyEliminated=remaining.filter(c=>attr(c,category,value)!==answer).map(c=>c.id);me.eliminated=new Set([...me.eliminated,...newlyEliminated]);r.lastQuestion={from:id,category,value,answer};r.turn=op.id;r.round++;guessState(r,id);guessState(r,op.id);emitRoom(r,'guess:question',{from:id,fromName:me.displayName,category,value,answer});});
 socket.on('guess:guess',({characterId})=>{const r=findRoom(id);if(!r||r.mode!=='guess'||r.phase!=='playing'||r.turn!==id)return;const me=r.players[id],op=r.players[me.opponent],g=Number(characterId);if(me.eliminated.has(g))return;const correct=g===op.secret;if(correct){endGame(r,id,`${CHARACTERS[g].name} was the secret character.`)}else{me.eliminated.add(g);r.lastQuestion={from:id,wrongGuess:g};r.turn=op.id;r.round++;guessState(r,id);guessState(r,op.id);emitRoom(r,'guess:wrong',{from:id,fromName:me.displayName,characterId:g});}});
 socket.on('game:leave',()=>leaveRoom(id,'Opponent left the game.'));
 socket.on('quick:tap',()=>{const r=findRoom(id);if(!r||r.mode!=='quick'||r.phase!=='go'||r.winner)return;const now=Date.now();r.taps??={};if(r.taps[id])return;r.taps[id]=now;if(Object.keys(r.taps).length===1){emitRoom(r,'quick:tap-seen',{playerId:id})}else{const entries=Object.entries(r.taps).sort((a,b)=>a[1]-b[1]);r.winner=entries[0][0];r.phase='ended';emitRoom(r,'quick:result',{winnerId:r.winner,times:Object.fromEntries(entries.map(([u,t])=>[u,t-r.goAt]))});finishRoomLater(r)}});
 socket.on('memory:flip',({index})=>{const r=findRoom(id);if(!r||r.mode!=='memory'||r.phase!=='playing'||r.turn!==id)return;r.revealed??=[];if(r.revealed.includes(index)||r.matched.includes(Math.floor(index/2)))return;if(r.revealed.length>=2)return;r.revealed.push(index);emitRoom(r,'memory:flip',{index});if(r.revealed.length===2){const[a,b]=r.revealed;setTimeout(()=>{if(r.deck[a]===r.deck[b]){const pair=r.deck[a];if(!r.matched.includes(pair)){r.matched.push(pair);r.scores[id]++;}emitRoom(r,'memory:pair',{indexes:[a,b],matched:r.matched,scores:r.scores,turn:r.turn,deck:r.deck})}else{r.turn=Object.keys(r.players).find(x=>x!==id);emitRoom(r,'memory:miss',{indexes:[a,b],turn:r.turn,scores:r.scores,deck:r.deck,matched:r.matched})}r.revealed=[];if(r.matched.length===8){const winner=Object.entries(r.scores).sort((a,b)=>b[1]-a[1])[0][0];r.phase='ended';emitRoom(r,'memory:result',{winnerId:winner,scores:r.scores});finishRoomLater(r)}},800)}});
 socket.on('connect:move',({column})=>{const r=findRoom(id);if(!r||r.mode!=='connect'||r.phase!=='playing'||r.turn!==id)return;let row=-1;for(let rr=5;rr>=0;rr--){if(r.board[rr*7+column]==null){row=rr;break}}if(row<0)return;const mark=r.players[id].mark||(r.players[id].mark=id===Object.keys(r.players)[0]?'red':'yellow');r.players[id].mark=mark;r.board[row*7+column]=mark;const win=checkConnect(r.board,row*7+column);if(win){r.phase='ended';r.winner=id;emitRoom(r,'connect:state',{board:r.board,turn:r.turn,winner:id});finishRoomLater(r)}else{r.turn=Object.keys(r.players).find(x=>x!==id);emitRoom(r,'connect:state',{board:r.board,turn:r.turn,winner:null})}});
 socket.on('number:answer',({value})=>{const r=findRoom(id);if(!r||r.mode!=='number'||r.phase!=='playing')return;if(r.answers?.[id])return;r.answers??={};const delta=Math.abs(Number(value)-r.target);r.answers[id]={value:Number(value),delta,time:Date.now()-r.startedAt};if(Object.keys(r.answers).length===2){const winner=Object.entries(r.answers).sort((a,b)=>a[1].delta-b[1].delta||a[1].time-b[1].time)[0][0];r.phase='ended';emitRoom(r,'number:result',{winnerId:winner,target:r.target,answers:r.answers});finishRoomLater(r)}});
 socket.on('disconnect',()=>{for(const mode of Object.keys(queues))queues[mode]=queues[mode].filter(x=>x!==id);leaveRoom(id,'Opponent disconnected.');sockets.delete(id);broadcast()});
});
function finishRoomLater(r){setTimeout(()=>{for(const id of Object.keys(r.players)){const s=sockets.get(id);if(s&&s.room===r.id){s.room=null;s.game=null}}rooms.delete(r.id);broadcast()},5000)}
function leaveRoom(id,reason){const r=findRoom(id);if(!r)return;const other=Object.keys(r.players).find(x=>x!==id);if(other&&sockets.has(other)){sockets.get(other).socket.emit('game:ended',{winnerId:other,reason});sockets.get(other).room=null;sockets.get(other).game=null}if(sockets.has(id)){sockets.get(id).room=null;sockets.get(id).game=null}sockets.get(id)?.socket.leave(r.id);rooms.delete(r.id);broadcast()}

app.post('/api/demo-login',(req,res)=>{const id='demo_'+crypto.randomUUID();const u=makeMem(id,{username:'demo',displayName:'Demo Player',avatarUrl:'https://cdn.discordapp.com/embed/avatars/0.png',demo:true});res.json({token:sign(u),user:pub(u,id)})});
app.get('/api/me',auth,(req,res)=>res.json({user:pub(req.user,req.uid)}));
app.get('/api/stats',auth,async(req,res)=>{const u=await getUser(req.uid);res.json({stats:{wins:u?.wins||0,losses:u?.losses||0,games:u?.games||0}})});
app.get('/api/leaderboard',async(req,res)=>{let rows=db?await User.find({demo:false}).sort({wins:-1,games:-1}).limit(100).lean():[...mem.values()].filter(x=>!x.demo);res.json({players:rows.map(x=>({displayName:x.displayName,avatarUrl:x.avatarUrl,wins:x.wins||0,losses:x.losses||0,games:x.games||0,winRate:x.games?Math.round(x.wins/x.games*100):0}))})});
app.get('/auth/discord',(req,res)=>{const state=jwt.sign({nonce:crypto.randomUUID()},SECRET,{expiresIn:'10m'});const p=new URLSearchParams({client_id:process.env.DISCORD_CLIENT_ID||'',response_type:'code',redirect_uri:process.env.DISCORD_REDIRECT_URI||'',scope:'identify',state});res.redirect('https://discord.com/oauth2/authorize?'+p)});
app.get('/auth/discord/callback',async(req,res)=>{try{jwt.verify(req.query.state,SECRET);const body=new URLSearchParams({client_id:process.env.DISCORD_CLIENT_ID,client_secret:process.env.DISCORD_CLIENT_SECRET,grant_type:'authorization_code',code:req.query.code,redirect_uri:process.env.DISCORD_REDIRECT_URI});const tr=await fetch('https://discord.com/api/oauth2/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});const token=await tr.json();if(!tr.ok)throw Error('token');const ur=await fetch('https://discord.com/api/users/@me',{headers:{Authorization:`Bearer ${token.access_token}`}});const p=await ur.json();const avatar=p.avatar?`https://cdn.discordapp.com/avatars/${p.id}/${p.avatar}.png?size=128`:`https://cdn.discordapp.com/embed/avatars/${Number(p.discriminator||0)%5}.png`;let u;if(db)u=await User.findOneAndUpdate({discordId:p.id},{discordId:p.id,username:p.username,displayName:p.global_name||p.username,avatarUrl:avatar,demo:false,lastSeen:new Date()},{upsert:true,new:true});else u=makeMem('d_'+p.id,{discordId:p.id,username:p.username,displayName:p.global_name||p.username,avatarUrl:avatar,demo:false});res.redirect(`${FRONT}/#token=${encodeURIComponent(sign(u))}`)}catch(e){console.error(e);res.status(400).send('Discord login failed')}});
server.listen(PORT,()=>console.log(`MiniVerse v3 backend on ${PORT}`));
